version: "3.7"
services:
  server:
    build: 
      dockerfile: server/Dockerfile
      context: .
    ports:
      - "5000:5000"
    volumes: 
      - ./server:/app
    environment: 
      FLASK_ENV: development
    restart: unless-stopped
    networks: 
      - prod
  web:
    build: 
      dockerfile: client/my-app/Dockerfile
      context: .
    ports:
      - "3000:3000"
    environment: 
      DANGEROUSLY_DISABLE_HOST_CHECK: "true"
    volumes:
      - ./client/my-app:/user/src/app
    networks: 
      - prod
    depends_on: 
      - server


networks:
  prod:
    external:
      name: prod